apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-exporter.fullname" . }}
  labels:
    app: {{ template "cert-exporter.name" . }}-cert-manager
    jobLabel: cert-exporter
{{- include "cert-exporter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: metrics
  selector:
{{- include "cert-exporter.labels" . | indent 4 }}
