name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ^1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Build snapshot
        run: make snapshot

      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
            !dist/*/*

      - name: Test certificate and kubeconfig
        run: |
          cd test/files
          ./test.sh

      - name: Test cert-manager-v1alpha1
        run: |
          cd test/cert-manager-v1alpha1
          ./test.sh

      - name: Test cert-manager-v1alpha2
        run: |
          cd test/cert-manager-v1alpha2
          ./test.sh
